/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as RenovacoesRouteImport } from './routes/renovacoes'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as HealthScoreRouteImport } from './routes/health-score'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendasIndexRouteImport } from './routes/vendas.index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as ConfiguracoesIndexRouteImport } from './routes/configuracoes.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as VendasPropostasRouteImport } from './routes/vendas.propostas'
import { Route as VendasMetasRouteImport } from './routes/vendas.metas'
import { Route as VendasLeadsRouteImport } from './routes/vendas.leads'
import { Route as FinanceiroVisaoGeralRouteImport } from './routes/financeiro.visao-geral'
import { Route as FinanceiroReguaRouteImport } from './routes/financeiro.regua'
import { Route as FinanceiroFluxoRouteImport } from './routes/financeiro.fluxo'
import { Route as FinanceiroAReceberRouteImport } from './routes/financeiro.a-receber'
import { Route as FinanceiroAPagarRouteImport } from './routes/financeiro.a-pagar'
import { Route as FerramentasWhatsappRouteImport } from './routes/ferramentas.whatsapp'
import { Route as FerramentasPautasRouteImport } from './routes/ferramentas.pautas'
import { Route as FerramentasGeradorRouteImport } from './routes/ferramentas.gerador'
import { Route as ConfiguracoesUsuariosRouteImport } from './routes/configuracoes.usuarios'
import { Route as ConfiguracoesClientesRouteImport } from './routes/configuracoes.clientes'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacoesRoute = RenovacoesRouteImport.update({
  id: '/renovacoes',
  path: '/renovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthScoreRoute = HealthScoreRouteImport.update({
  id: '/health-score',
  path: '/health-score',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasIndexRoute = VendasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendasRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const ConfiguracoesIndexRoute = ConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientesRoute,
} as any)
const VendasPropostasRoute = VendasPropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => VendasRoute,
} as any)
const VendasMetasRoute = VendasMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => VendasRoute,
} as any)
const VendasLeadsRoute = VendasLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => VendasRoute,
} as any)
const FinanceiroVisaoGeralRoute = FinanceiroVisaoGeralRouteImport.update({
  id: '/visao-geral',
  path: '/visao-geral',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroReguaRoute = FinanceiroReguaRouteImport.update({
  id: '/regua',
  path: '/regua',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroFluxoRoute = FinanceiroFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroAReceberRoute = FinanceiroAReceberRouteImport.update({
  id: '/a-receber',
  path: '/a-receber',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroAPagarRoute = FinanceiroAPagarRouteImport.update({
  id: '/a-pagar',
  path: '/a-pagar',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FerramentasWhatsappRoute = FerramentasWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasPautasRoute = FerramentasPautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasGeradorRoute = FerramentasGeradorRouteImport.update({
  id: '/gerador',
  path: '/gerador',
  getParentRoute: () => FerramentasRoute,
} as any)
const ConfiguracoesUsuariosRoute = ConfiguracoesUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ConfiguracoesClientesRoute = ConfiguracoesClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => ConfiguracoesRoute,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/health-score': typeof HealthScoreRoute
  '/planejamento': typeof PlanejamentoRoute
  '/renovacoes': typeof RenovacoesRoute
  '/tarefas': typeof TarefasRoute
  '/vendas': typeof VendasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/clientes': typeof ConfiguracoesClientesRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/ferramentas/gerador': typeof FerramentasGeradorRoute
  '/ferramentas/pautas': typeof FerramentasPautasRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/financeiro/a-pagar': typeof FinanceiroAPagarRoute
  '/financeiro/a-receber': typeof FinanceiroAReceberRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/regua': typeof FinanceiroReguaRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/leads': typeof VendasLeadsRoute
  '/vendas/metas': typeof VendasMetasRoute
  '/vendas/propostas': typeof VendasPropostasRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/health-score': typeof HealthScoreRoute
  '/planejamento': typeof PlanejamentoRoute
  '/renovacoes': typeof RenovacoesRoute
  '/tarefas': typeof TarefasRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/clientes': typeof ConfiguracoesClientesRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/ferramentas/gerador': typeof FerramentasGeradorRoute
  '/ferramentas/pautas': typeof FerramentasPautasRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/financeiro/a-pagar': typeof FinanceiroAPagarRoute
  '/financeiro/a-receber': typeof FinanceiroAReceberRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/regua': typeof FinanceiroReguaRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/leads': typeof VendasLeadsRoute
  '/vendas/metas': typeof VendasMetasRoute
  '/vendas/propostas': typeof VendasPropostasRoute
  '/clientes': typeof ClientesIndexRoute
  '/configuracoes': typeof ConfiguracoesIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/vendas': typeof VendasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRouteWithChildren
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/health-score': typeof HealthScoreRoute
  '/planejamento': typeof PlanejamentoRoute
  '/renovacoes': typeof RenovacoesRoute
  '/tarefas': typeof TarefasRoute
  '/vendas': typeof VendasRouteWithChildren
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/clientes': typeof ConfiguracoesClientesRoute
  '/configuracoes/usuarios': typeof ConfiguracoesUsuariosRoute
  '/ferramentas/gerador': typeof FerramentasGeradorRoute
  '/ferramentas/pautas': typeof FerramentasPautasRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/financeiro/a-pagar': typeof FinanceiroAPagarRoute
  '/financeiro/a-receber': typeof FinanceiroAReceberRoute
  '/financeiro/fluxo': typeof FinanceiroFluxoRoute
  '/financeiro/regua': typeof FinanceiroReguaRoute
  '/financeiro/visao-geral': typeof FinanceiroVisaoGeralRoute
  '/vendas/leads': typeof VendasLeadsRoute
  '/vendas/metas': typeof VendasMetasRoute
  '/vendas/propostas': typeof VendasPropostasRoute
  '/clientes/': typeof ClientesIndexRoute
  '/configuracoes/': typeof ConfiguracoesIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/vendas/': typeof VendasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/ferramentas'
    | '/financeiro'
    | '/health-score'
    | '/planejamento'
    | '/renovacoes'
    | '/tarefas'
    | '/vendas'
    | '/clientes/$id'
    | '/configuracoes/clientes'
    | '/configuracoes/usuarios'
    | '/ferramentas/gerador'
    | '/ferramentas/pautas'
    | '/ferramentas/whatsapp'
    | '/financeiro/a-pagar'
    | '/financeiro/a-receber'
    | '/financeiro/fluxo'
    | '/financeiro/regua'
    | '/financeiro/visao-geral'
    | '/vendas/leads'
    | '/vendas/metas'
    | '/vendas/propostas'
    | '/clientes/'
    | '/configuracoes/'
    | '/ferramentas/'
    | '/financeiro/'
    | '/vendas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/health-score'
    | '/planejamento'
    | '/renovacoes'
    | '/tarefas'
    | '/clientes/$id'
    | '/configuracoes/clientes'
    | '/configuracoes/usuarios'
    | '/ferramentas/gerador'
    | '/ferramentas/pautas'
    | '/ferramentas/whatsapp'
    | '/financeiro/a-pagar'
    | '/financeiro/a-receber'
    | '/financeiro/fluxo'
    | '/financeiro/regua'
    | '/financeiro/visao-geral'
    | '/vendas/leads'
    | '/vendas/metas'
    | '/vendas/propostas'
    | '/clientes'
    | '/configuracoes'
    | '/ferramentas'
    | '/financeiro'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/ferramentas'
    | '/financeiro'
    | '/health-score'
    | '/planejamento'
    | '/renovacoes'
    | '/tarefas'
    | '/vendas'
    | '/clientes/$id'
    | '/configuracoes/clientes'
    | '/configuracoes/usuarios'
    | '/ferramentas/gerador'
    | '/ferramentas/pautas'
    | '/ferramentas/whatsapp'
    | '/financeiro/a-pagar'
    | '/financeiro/a-receber'
    | '/financeiro/fluxo'
    | '/financeiro/regua'
    | '/financeiro/visao-geral'
    | '/vendas/leads'
    | '/vendas/metas'
    | '/vendas/propostas'
    | '/clientes/'
    | '/configuracoes/'
    | '/ferramentas/'
    | '/financeiro/'
    | '/vendas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRouteWithChildren
  FerramentasRoute: typeof FerramentasRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  HealthScoreRoute: typeof HealthScoreRoute
  PlanejamentoRoute: typeof PlanejamentoRoute
  RenovacoesRoute: typeof RenovacoesRoute
  TarefasRoute: typeof TarefasRoute
  VendasRoute: typeof VendasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacoes': {
      id: '/renovacoes'
      path: '/renovacoes'
      fullPath: '/renovacoes'
      preLoaderRoute: typeof RenovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-score': {
      id: '/health-score'
      path: '/health-score'
      fullPath: '/health-score'
      preLoaderRoute: typeof HealthScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas/': {
      id: '/vendas/'
      path: '/'
      fullPath: '/vendas/'
      preLoaderRoute: typeof VendasIndexRouteImport
      parentRoute: typeof VendasRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/configuracoes/': {
      id: '/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof ConfiguracoesIndexRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/vendas/propostas': {
      id: '/vendas/propostas'
      path: '/propostas'
      fullPath: '/vendas/propostas'
      preLoaderRoute: typeof VendasPropostasRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/metas': {
      id: '/vendas/metas'
      path: '/metas'
      fullPath: '/vendas/metas'
      preLoaderRoute: typeof VendasMetasRouteImport
      parentRoute: typeof VendasRoute
    }
    '/vendas/leads': {
      id: '/vendas/leads'
      path: '/leads'
      fullPath: '/vendas/leads'
      preLoaderRoute: typeof VendasLeadsRouteImport
      parentRoute: typeof VendasRoute
    }
    '/financeiro/visao-geral': {
      id: '/financeiro/visao-geral'
      path: '/visao-geral'
      fullPath: '/financeiro/visao-geral'
      preLoaderRoute: typeof FinanceiroVisaoGeralRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/regua': {
      id: '/financeiro/regua'
      path: '/regua'
      fullPath: '/financeiro/regua'
      preLoaderRoute: typeof FinanceiroReguaRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/fluxo': {
      id: '/financeiro/fluxo'
      path: '/fluxo'
      fullPath: '/financeiro/fluxo'
      preLoaderRoute: typeof FinanceiroFluxoRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/a-receber': {
      id: '/financeiro/a-receber'
      path: '/a-receber'
      fullPath: '/financeiro/a-receber'
      preLoaderRoute: typeof FinanceiroAReceberRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/a-pagar': {
      id: '/financeiro/a-pagar'
      path: '/a-pagar'
      fullPath: '/financeiro/a-pagar'
      preLoaderRoute: typeof FinanceiroAPagarRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/ferramentas/whatsapp': {
      id: '/ferramentas/whatsapp'
      path: '/whatsapp'
      fullPath: '/ferramentas/whatsapp'
      preLoaderRoute: typeof FerramentasWhatsappRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/pautas': {
      id: '/ferramentas/pautas'
      path: '/pautas'
      fullPath: '/ferramentas/pautas'
      preLoaderRoute: typeof FerramentasPautasRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/gerador': {
      id: '/ferramentas/gerador'
      path: '/gerador'
      fullPath: '/ferramentas/gerador'
      preLoaderRoute: typeof FerramentasGeradorRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/configuracoes/usuarios': {
      id: '/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof ConfiguracoesUsuariosRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/configuracoes/clientes': {
      id: '/configuracoes/clientes'
      path: '/clientes'
      fullPath: '/configuracoes/clientes'
      preLoaderRoute: typeof ConfiguracoesClientesRouteImport
      parentRoute: typeof ConfiguracoesRoute
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ConfiguracoesRouteChildren {
  ConfiguracoesClientesRoute: typeof ConfiguracoesClientesRoute
  ConfiguracoesUsuariosRoute: typeof ConfiguracoesUsuariosRoute
  ConfiguracoesIndexRoute: typeof ConfiguracoesIndexRoute
}

const ConfiguracoesRouteChildren: ConfiguracoesRouteChildren = {
  ConfiguracoesClientesRoute: ConfiguracoesClientesRoute,
  ConfiguracoesUsuariosRoute: ConfiguracoesUsuariosRoute,
  ConfiguracoesIndexRoute: ConfiguracoesIndexRoute,
}

const ConfiguracoesRouteWithChildren = ConfiguracoesRoute._addFileChildren(
  ConfiguracoesRouteChildren,
)

interface FerramentasRouteChildren {
  FerramentasGeradorRoute: typeof FerramentasGeradorRoute
  FerramentasPautasRoute: typeof FerramentasPautasRoute
  FerramentasWhatsappRoute: typeof FerramentasWhatsappRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasGeradorRoute: FerramentasGeradorRoute,
  FerramentasPautasRoute: FerramentasPautasRoute,
  FerramentasWhatsappRoute: FerramentasWhatsappRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroAPagarRoute: typeof FinanceiroAPagarRoute
  FinanceiroAReceberRoute: typeof FinanceiroAReceberRoute
  FinanceiroFluxoRoute: typeof FinanceiroFluxoRoute
  FinanceiroReguaRoute: typeof FinanceiroReguaRoute
  FinanceiroVisaoGeralRoute: typeof FinanceiroVisaoGeralRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroAPagarRoute: FinanceiroAPagarRoute,
  FinanceiroAReceberRoute: FinanceiroAReceberRoute,
  FinanceiroFluxoRoute: FinanceiroFluxoRoute,
  FinanceiroReguaRoute: FinanceiroReguaRoute,
  FinanceiroVisaoGeralRoute: FinanceiroVisaoGeralRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface VendasRouteChildren {
  VendasLeadsRoute: typeof VendasLeadsRoute
  VendasMetasRoute: typeof VendasMetasRoute
  VendasPropostasRoute: typeof VendasPropostasRoute
  VendasIndexRoute: typeof VendasIndexRoute
}

const VendasRouteChildren: VendasRouteChildren = {
  VendasLeadsRoute: VendasLeadsRoute,
  VendasMetasRoute: VendasMetasRoute,
  VendasPropostasRoute: VendasPropostasRoute,
  VendasIndexRoute: VendasIndexRoute,
}

const VendasRouteWithChildren =
  VendasRoute._addFileChildren(VendasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRouteWithChildren,
  FerramentasRoute: FerramentasRouteWithChildren,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  HealthScoreRoute: HealthScoreRoute,
  PlanejamentoRoute: PlanejamentoRoute,
  RenovacoesRoute: RenovacoesRoute,
  TarefasRoute: TarefasRoute,
  VendasRoute: VendasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
